INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Carlos Ulyses Largaespada','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Judith Esther Reyes Higgins','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Luz Guianbelly Dallas Contreras','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Mayde  Diaz Alvarez','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Maria Maddalena Castellaneta','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Gloria Patricia Taylor','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Larisa  Whitaker','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Elizabeth M Ruz','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Juan Ramon Vega','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Ronaldo  Loaisiga','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Reinaldo  Garcia','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Altery  Fleurant','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Luz R Castillo','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Steven John Valentino','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Jasmine  Cruz','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Tymesha O''Neka Jones','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Julio C Salguero','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Galite  Zohar','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Tiffany  Hervis','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Eric Andrew Fernandez','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Guianeya De Las Mercedes Diaz','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Kayla  Pacheco','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Gail Delores Wilson','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'James  Harris','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Jina  Hernandez','Republican');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Trevor James Lafargue','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Maxine Irene Luster','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Franklin L Smith','Democrat');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Rainer Javier Lorenzo','Other');
INSERT INTO voter_list(region_id,name_full,party) VALUES (496,'Albanery  Badia','Democrat');
